import './globals.css';
import clsx from 'clsx';
import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';
import React from 'react';

import { Layout } from '@/components/Layout';
import RiskCautionModal from '@/components/Modals/RiskCautionModal';
import { Sidebar } from '@/components/Sidebar';
import { albertText, montserrat, arimo } from '@/utils/fonts';

export const metadata: Metadata = {
  title: `Alchemestry ${process.env.NEXT_PUBLIC_TITLE_POSTFIX}`,
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className="scrollbar-none">
        <div
          className={clsx(
            'bg-primary',
            albertText.variable,
            montserrat.variable,
            arimo.variable,
            'flex h-full min-h-full w-full font-montserrat text-primary',
          )}
        >
          <Sidebar />
          <Layout>{children}</Layout>
          <RiskCautionModal />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
