import './globals.css';
import clsx from 'clsx';
import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';
import React from 'react';

import { Sidebar } from '@/components/Sidebar';
import { albertText, montserrat } from '@/utils/fonts';

export const metadata: Metadata = {
  title: `Alchemestry ${process.env.NEXT_PUBLIC_TITLE_POSTFIX}`,
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <div
          className={clsx(
            'bg-primary',
            albertText.variable,
            montserrat.variable,
            'flex h-full w-full flex-col font-montserrat text-primary md:flex-row',
          )}
        >
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
